import os
import random
import time

os.system('cls')
print ('Command:')
print ('hack: Start hacking to the attached server (only used after connecting to the server and Install the hacking tool on the server)')
print ('')
c = input()

os.system('cls')
if c == "hack":
        print ('start the attack!')
        rtm2 = 0.5
        time.sleep (rtm2)
        print ('All processes preventing hacking are shutting down.')
        print ('[/------------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[//-----------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[///----------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[////---------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[/////--------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[//////-------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[///////------]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[////////-----]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[/////////----]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[//////////---]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[///////////--]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[////////////-]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('All processes preventing hacking are shutting down.')
        print ('[/////////////]')
        time.sleep (rtm2)
        os.system ('cls')
        print ('First attack successful!')
        print ("We're preparing a DDoS attack. Please wait.")
        time.sleep (3)
        print ('Initiate a DDoS attack.')
        print ('Sending 30 million packets via zombie pc!!!!')
        wh = 0
        while wh < 10:
            wh = wh + 1
            print ('Packet sending succeeded.')
            print ("We've finished all the attacks. Close the program in 10 seconds.")
            time.sleep(10)
            exit ()
        
# If enter another command / 유효하지 명령어를 입력했을 때
else:
    print ('Either you entered an invalid command, or you entered a command that is currently unavailable.')
    print ('Press any key to restart the program. (a return to the former times)')
    input()
    os.system ('python gf-sh-dm.py')
    exit()

